package vista;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import preguntas.y.respuestas.clases.Categoria;
import preguntas.y.respuestas.clases.DAOS;
import preguntas.y.respuestas.clases.Juego;
import preguntas.y.respuestas.clases.Pregunta;
import preguntas.y.respuestas.clases.Premio;
import preguntas.y.respuestas.clases.Respuesta;
import preguntas.y.respuestas.clases.Ronda;

/**
 *
 * @author Daniel Alzate
 */
public class pantalla_de_juego extends javax.swing.JFrame {

    /**
     * Creates new form pantalla_de_juego
     */
    public pantalla_de_juego(DAOS daos) {
        initComponents();
        this.daos = daos;
        rondas = new Ronda();
        premio = new Premio();
    }

    public void iniciar() {
        juego();
        this.setVisible(true);
    }

    private int xMouse, yMouse;
    private Ronda rondas;
    private Pregunta preguntas;
    private ArrayList<Respuesta> respuestas;
    private DAOS daos;
    private Categoria categorias;
    private Premio premio;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        btnVolver = new javax.swing.JPanel();
        volver = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pregunta = new javax.swing.JTextArea();
        btnA = new javax.swing.JPanel();
        respuestaA = new java.awt.TextField();
        btnC = new javax.swing.JPanel();
        respuestaC = new java.awt.TextField();
        btnB = new javax.swing.JPanel();
        respuestaB = new java.awt.TextField();
        btnD = new javax.swing.JPanel();
        respuestaD = new java.awt.TextField();
        btnRendirse = new javax.swing.JPanel();
        rendirse = new javax.swing.JLabel();
        ronda = new javax.swing.JLabel();
        puntuacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        panelSuperior.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelSuperiorMouseDragged(evt);
            }
        });
        panelSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSuperiorMousePressed(evt);
            }
        });

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/brain (1).png"))); // NOI18N

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 385, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 30));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });

        volver.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(0, 0, 0));
        volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver (1).png"))); // NOI18N

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(volver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(volver, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 30, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(0, 0, 51));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("QUIZ!");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exploding (1)_1.png"))); // NOI18N

        pregunta.setEditable(false);
        pregunta.setBackground(new java.awt.Color(255, 255, 255));
        pregunta.setColumns(20);
        pregunta.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        pregunta.setForeground(new java.awt.Color(0, 0, 51));
        pregunta.setRows(5);
        pregunta.setBorder(null);
        jScrollPane1.setViewportView(pregunta);

        btnA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAMouseClicked(evt);
            }
        });

        respuestaA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        respuestaA.setEditable(false);
        respuestaA.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        respuestaA.setForeground(new java.awt.Color(0, 0, 51));
        respuestaA.setText("A.");
        respuestaA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                respuestaAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnALayout = new javax.swing.GroupLayout(btnA);
        btnA.setLayout(btnALayout);
        btnALayout.setHorizontalGroup(
            btnALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(respuestaA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btnALayout.setVerticalGroup(
            btnALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(respuestaA, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        respuestaC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        respuestaC.setEditable(false);
        respuestaC.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        respuestaC.setForeground(new java.awt.Color(0, 0, 51));
        respuestaC.setText("C.");
        respuestaC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                respuestaCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCLayout = new javax.swing.GroupLayout(btnC);
        btnC.setLayout(btnCLayout);
        btnCLayout.setHorizontalGroup(
            btnCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(respuestaC, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnCLayout.setVerticalGroup(
            btnCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(respuestaC, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        btnB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        respuestaB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        respuestaB.setEditable(false);
        respuestaB.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        respuestaB.setForeground(new java.awt.Color(0, 0, 51));
        respuestaB.setText("B.");
        respuestaB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                respuestaBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnBLayout = new javax.swing.GroupLayout(btnB);
        btnB.setLayout(btnBLayout);
        btnBLayout.setHorizontalGroup(
            btnBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(respuestaB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnBLayout.setVerticalGroup(
            btnBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(respuestaB, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        btnD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        respuestaD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        respuestaD.setEditable(false);
        respuestaD.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        respuestaD.setForeground(new java.awt.Color(0, 0, 51));
        respuestaD.setText("D.");
        respuestaD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                respuestaDMouseClicked(evt);
            }
        });
        respuestaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestaDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnDLayout = new javax.swing.GroupLayout(btnD);
        btnD.setLayout(btnDLayout);
        btnDLayout.setHorizontalGroup(
            btnDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(respuestaD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btnDLayout.setVerticalGroup(
            btnDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(respuestaD, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnRendirse.setBackground(new java.awt.Color(0, 0, 51));
        btnRendirse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRendirse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRendirseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRendirseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRendirseMouseExited(evt);
            }
        });

        rendirse.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rendirse.setForeground(new java.awt.Color(255, 255, 255));
        rendirse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/darse-por-vencido.png"))); // NOI18N
        rendirse.setText("RENDIRSE");

        javax.swing.GroupLayout btnRendirseLayout = new javax.swing.GroupLayout(btnRendirse);
        btnRendirse.setLayout(btnRendirseLayout);
        btnRendirseLayout.setHorizontalGroup(
            btnRendirseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rendirse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnRendirseLayout.setVerticalGroup(
            btnRendirseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rendirse, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        ronda.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        ronda.setForeground(new java.awt.Color(0, 0, 51));
        ronda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ronda.setText("Ronda");

        puntuacion.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        puntuacion.setForeground(new java.awt.Color(0, 0, 51));
        puntuacion.setText("Puntuacion:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRendirse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ronda, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(puntuacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ronda)
                    .addComponent(puntuacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnRendirse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelSuperiorMouseDragged

    private void panelSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSuperiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelSuperiorMousePressed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        inicio.main(daos);
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        btnVolver.setBackground(new Color(0, 255, 0));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        btnVolver.setBackground(Color.white);
    }//GEN-LAST:event_btnVolverMouseExited

    private void respuestaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuestaDActionPerformed

    private void btnRendirseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRendirseMouseEntered
        btnRendirse.setBackground(Color.red);
    }//GEN-LAST:event_btnRendirseMouseEntered

    private void btnRendirseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRendirseMouseExited
        btnRendirse.setBackground(new Color(0, 0, 51));
    }//GEN-LAST:event_btnRendirseMouseExited

    private void btnRendirseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRendirseMouseClicked
        pantalla_final.main(daos, premio);
        this.dispose();
    }//GEN-LAST:event_btnRendirseMouseClicked

    private void btnAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAMouseClicked

    }//GEN-LAST:event_btnAMouseClicked

    private void respuestaAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respuestaAMouseClicked
        if (respuestas.get(0).isCorrecta()) {
            if (rondas.getNumRonda() == 5) {
                premio.setMaximo();
                try {
                    finalJuego();
                } catch (SQLException ex) {
                    Logger.getLogger(pantalla_de_juego.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                rondas.avanzarRonda();
                juego();
            }
        } else {
            premio.reset();
            try {
                finalJuego();
            } catch (SQLException ex) {
                Logger.getLogger(pantalla_de_juego.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_respuestaAMouseClicked

    private void respuestaCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respuestaCMouseClicked
        if (respuestas.get(2).isCorrecta()) {
            if (rondas.getNumRonda() == 5) {
                premio.setMaximo();
                try {
                    finalJuego();
                } catch (SQLException ex) {
                    Logger.getLogger(pantalla_de_juego.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                rondas.avanzarRonda();
                juego();
            }

        } else {
            premio.reset();
            try {
                finalJuego();
            } catch (SQLException ex) {
                Logger.getLogger(pantalla_de_juego.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_respuestaCMouseClicked

    private void respuestaBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respuestaBMouseClicked
        if (respuestas.get(1).isCorrecta()) {
            if (rondas.getNumRonda() == 5) {
                premio.setMaximo();
                try {
                    finalJuego();
                } catch (SQLException ex) {
                    Logger.getLogger(pantalla_de_juego.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                rondas.avanzarRonda();
                juego();
            }
        } else {
            premio.reset();
            try {
                finalJuego();
            } catch (SQLException ex) {
                Logger.getLogger(pantalla_de_juego.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_respuestaBMouseClicked

    private void respuestaDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respuestaDMouseClicked
        if (respuestas.get(3).isCorrecta()) {
            if (rondas.getNumRonda() == 5) {
                premio.setMaximo();
                try {
                    finalJuego();
                } catch (SQLException ex) {
                    Logger.getLogger(pantalla_de_juego.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                rondas.avanzarRonda();
                juego();
            }
        } else {
            premio.reset();
            try {
                finalJuego();
            } catch (SQLException ex) {
                Logger.getLogger(pantalla_de_juego.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_respuestaDMouseClicked

    /**
     */
    public static void main(DAOS daos) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla_de_juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla_de_juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla_de_juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla_de_juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    private void juego() {
        categorias = daos.getCategoria(rondas.getNumRonda());
        preguntas = daos.getPregunta(categorias);
        respuestas = daos.getRespuestas(preguntas.getRespuestas());
        premio.setDinero(rondas);
        puntuacion.setText("PUNTUACION: " + premio.getDinero());
        pregunta.setText(preguntas.getPregunta());
        respuestaA.setText(respuestas.get(0).getRespuesta());
        respuestaB.setText(respuestas.get(1).getRespuesta());
        respuestaC.setText(respuestas.get(2).getRespuesta());
        respuestaD.setText(respuestas.get(3).getRespuesta());
        ronda.setText("RONDA " + rondas.getNumRonda());
    }

    private void finalJuego() throws SQLException {
        Juego juego = new Juego(daos.getJugador(), premio);
        sql.inserciones.insertarJuego(juego);
        pantalla_final.main(daos, premio);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnA;
    private javax.swing.JPanel btnB;
    private javax.swing.JPanel btnC;
    private javax.swing.JPanel btnD;
    private javax.swing.JPanel btnRendirse;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTextArea pregunta;
    private javax.swing.JLabel puntuacion;
    private javax.swing.JLabel rendirse;
    private java.awt.TextField respuestaA;
    private java.awt.TextField respuestaB;
    private java.awt.TextField respuestaC;
    private java.awt.TextField respuestaD;
    private javax.swing.JLabel ronda;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
